import "./app.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "@/shared/providers";

const Pretendard = localFont({
  src: "../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  adjustFontFallback: false,
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ko">
      <body className={Pretendard.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
