import "./app.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import MazeUs from "@/shared/components/maze-us";
import Providers from "@/shared/providers";
import DialogProvider from "@/shared/providers/modules/dialog-provider";

const Pretendard = localFont({
  src: "../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  adjustFontFallback: false,
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ko">
      <head>
        <MazeUs />
      </head>
      <body className={Pretendard.variable}>
        <Providers>
          {children}
          {/* TODO: fallback UI 수정 */}
          <Suspense fallback={null}>
            <DialogProvider />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
