import "./app.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { JotaiProvider } from "@/shared/providers/jotai-provider";
import QueryProvider from "@/shared/providers/query-provider";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <JotaiProvider>
          <QueryProvider>{children}</QueryProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
