export const bgColorOptions = [
  "bg-white",
  "bg-black",
  "bg-primary",

  // neutral
  "bg-neutral-100",
  "bg-neutral-99",
  "bg-neutral-98",
  "bg-neutral-95",
  "bg-neutral-90",
  "bg-neutral-80",
  "bg-neutral-70",
  "bg-neutral-60",
  "bg-neutral-50",
  "bg-neutral-40",
  "bg-neutral-35",
  "bg-neutral-30",
  "bg-neutral-25",
  "bg-neutral-20",
  "bg-neutral-15",
  "bg-neutral-10",
  "bg-neutral-5",
  "bg-neutral-0",

  // neutral-variant
  "bg-neutral-variant-100",
  "bg-neutral-variant-99",
  "bg-neutral-variant-98",
  "bg-neutral-variant-95",
  "bg-neutral-variant-90",
  "bg-neutral-variant-80",
  "bg-neutral-variant-70",
  "bg-neutral-variant-60",
  "bg-neutral-variant-50",
  "bg-neutral-variant-40",
  "bg-neutral-variant-35",
  "bg-neutral-variant-30",
  "bg-neutral-variant-25",
  "bg-neutral-variant-20",
  "bg-neutral-variant-15",
  "bg-neutral-variant-10",
  "bg-neutral-variant-5",
  "bg-neutral-variant-0",

  // primary
  "bg-primary-100",
  "bg-primary-99",
  "bg-primary-98",
  "bg-primary-95",
  "bg-primary-90",
  "bg-primary-80",
  "bg-primary-70",
  "bg-primary-60",
  "bg-primary-50",
  "bg-primary-40",
  "bg-primary-35",
  "bg-primary-30",
  "bg-primary-25",
  "bg-primary-20",
  "bg-primary-15",
  "bg-primary-10",
  "bg-primary-5",
  "bg-primary-0",

  // secondary
  "bg-secondary-100",
  "bg-secondary-99",
  "bg-secondary-98",
  "bg-secondary-95",
  "bg-secondary-90",
  "bg-secondary-80",
  "bg-secondary-70",
  "bg-secondary-60",
  "bg-secondary-50",
  "bg-secondary-40",
  "bg-secondary-35",
  "bg-secondary-30",
  "bg-secondary-25",
  "bg-secondary-20",
  "bg-secondary-15",
  "bg-secondary-10",
  "bg-secondary-5",
  "bg-secondary-0",

  // error
  "bg-error-100",
  "bg-error-99",
  "bg-error-98",
  "bg-error-95",
  "bg-error-90",
  "bg-error-80",
  "bg-error-70",
  "bg-error-60",
  "bg-error-50",
  "bg-error-40",
  "bg-error-35",
  "bg-error-30",
  "bg-error-25",
  "bg-error-20",
  "bg-error-15",
  "bg-error-10",
  "bg-error-5",
  "bg-error-0",

  // tertiary
  "bg-tertiary-100",
  "bg-tertiary-99",
  "bg-tertiary-98",
  "bg-tertiary-95",
  "bg-tertiary-90",
  "bg-tertiary-80",
  "bg-tertiary-70",
  "bg-tertiary-60",
  "bg-tertiary-50",
  "bg-tertiary-40",
  "bg-tertiary-35",
  "bg-tertiary-30",
  "bg-tertiary-25",
  "bg-tertiary-20",
  "bg-tertiary-15",
  "bg-tertiary-10",
  "bg-tertiary-5",
  "bg-tertiary-0",
] as const;

export const textColorOptions = [
  "text-white",
  "text-black",
  "text-primary",

  // neutral
  "text-neutral-100",
  "text-neutral-99",
  "text-neutral-98",
  "text-neutral-95",
  "text-neutral-90",
  "text-neutral-80",
  "text-neutral-70",
  "text-neutral-60",
  "text-neutral-50",
  "text-neutral-40",
  "text-neutral-35",
  "text-neutral-30",
  "text-neutral-25",
  "text-neutral-20",
  "text-neutral-15",
  "text-neutral-10",
  "text-neutral-5",
  "text-neutral-0",

  // neutral-variant
  "text-neutral-variant-100",
  "text-neutral-variant-99",
  "text-neutral-variant-98",
  "text-neutral-variant-95",
  "text-neutral-variant-90",
  "text-neutral-variant-80",
  "text-neutral-variant-70",
  "text-neutral-variant-60",
  "text-neutral-variant-50",
  "text-neutral-variant-40",
  "text-neutral-variant-35",
  "text-neutral-variant-30",
  "text-neutral-variant-25",
  "text-neutral-variant-20",
  "text-neutral-variant-15",
  "text-neutral-variant-10",
  "text-neutral-variant-5",
  "text-neutral-variant-0",

  // primary
  "text-primary-100",
  "text-primary-99",
  "text-primary-98",
  "text-primary-95",
  "text-primary-90",
  "text-primary-80",
  "text-primary-70",
  "text-primary-60",
  "text-primary-50",
  "text-primary-40",
  "text-primary-35",
  "text-primary-30",
  "text-primary-25",
  "text-primary-20",
  "text-primary-15",
  "text-primary-10",
  "text-primary-5",
  "text-primary-0",

  // secondary
  "text-secondary-100",
  "text-secondary-99",
  "text-secondary-98",
  "text-secondary-95",
  "text-secondary-90",
  "text-secondary-80",
  "text-secondary-70",
  "text-secondary-60",
  "text-secondary-50",
  "text-secondary-40",
  "text-secondary-35",
  "text-secondary-30",
  "text-secondary-25",
  "text-secondary-20",
  "text-secondary-15",
  "text-secondary-10",
  "text-secondary-5",
  "text-secondary-0",

  // error
  "text-error-100",
  "text-error-99",
  "text-error-98",
  "text-error-95",
  "text-error-90",
  "text-error-80",
  "text-error-70",
  "text-error-60",
  "text-error-50",
  "text-error-40",
  "text-error-35",
  "text-error-30",
  "text-error-25",
  "text-error-20",
  "text-error-15",
  "text-error-10",
  "text-error-5",
  "text-error-0",

  // tertiary
  "text-tertiary-100",
  "text-tertiary-99",
  "text-tertiary-98",
  "text-tertiary-95",
  "text-tertiary-90",
  "text-tertiary-80",
  "text-tertiary-70",
  "text-tertiary-60",
  "text-tertiary-50",
  "text-tertiary-40",
  "text-tertiary-35",
  "text-tertiary-30",
  "text-tertiary-25",
  "text-tertiary-20",
  "text-tertiary-15",
  "text-tertiary-10",
  "text-tertiary-5",
  "text-tertiary-0",
] as const;

export const typoOptions = [
  "text-title1-semi36",
  "text-title2-medi28",
  "text-title3-bold24",
  "text-heading1-semi20",
  "text-heading2-semi18",
  "text-heading2-medi18",
  "text-body1-semi16",
  "text-body1-medi16",
  "text-body1-regular16",
  "text-body2-medi14",
  "text-body2-regular14",
  "text-caption1-semi12",
  "text-caption1-medi12",
  "text-caption2-medi11",
  "text-caption2-regular11",
] as const;

export type Typo = (typeof typoOptions)[number];
export type BgColor = (typeof bgColorOptions)[number];
export type TextColor = (typeof textColorOptions)[number];
