/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YAPP26 WEB2
 * SSOK 서비스 API 명세
 * OpenAPI spec version: v1
 */
/**
 * 응답 유형
 */
export type StandardResponseUserResponseResponseType = "SUCCESS" | "ERROR";
/**
 * API 응답의 표준 형식을 정의하는 클래스
 */
export interface StandardResponseUserResponse {
  /** 응답 유형 */
  responseType?: StandardResponseUserResponseResponseType;
  /** 응답 결과 데이터 */
  result?: UserResponse;
}

export interface UserResponse {
  id?: number;
  name?: string;
}

/**
 * 응답 유형
 */
export type StandardResponseStringResponseType = "SUCCESS" | "ERROR";
/**
 * API 응답의 표준 형식을 정의하는 클래스
 */
export interface StandardResponseString {
  /** 응답 유형 */
  responseType?: StandardResponseStringResponseType;
  /** 응답 결과 데이터 */
  result?: string;
}

export interface AccommodationPageResponse {
  accommodations?: AccommodationResponse[];
  hasNext?: boolean;
}

export interface AccommodationResponse {
  id?: number;
  userId?: number;
  urlTest?: string;
  siteName?: string;
  memo?: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  tableId?: number;
  accommodationName?: string;
  images?: string[];
  address?: string;
  latitude?: number;
  longitude?: number;
  lowestPrice?: number;
  highestPrice?: number;
  currency?: string;
  reviewScore?: number;
  cleanlinessScore?: number;
  reviewSummary?: string;
  hotelId?: number;
  nearbyAttractions?: Attraction[];
  nearbyTransportation?: Transportation[];
  amenities?: Amenity[];
  checkInTime?: CheckTime;
  checkOutTime?: CheckTime;
}

export interface Amenity {
  type?: string;
  available?: boolean;
  description?: string;
}

export interface Attraction {
  name?: string;
  type?: string;
  latitude?: number;
  longitude?: number;
  distance?: string;
  byFoot?: DistanceInfo;
  byCar?: DistanceInfo;
}

export interface CheckTime {
  checkInTimeFrom?: string;
  checkInTimeTo?: string;
}

export interface DistanceInfo {
  distance?: string;
  time?: string;
}

/**
 * 응답 유형
 */
export type StandardResponseAccommodationPageResponseResponseType =
  | "SUCCESS"
  | "ERROR";
/**
 * API 응답의 표준 형식을 정의하는 클래스
 */
export interface StandardResponseAccommodationPageResponse {
  /** 응답 유형 */
  responseType?: StandardResponseAccommodationPageResponseResponseType;
  /** 응답 결과 데이터 */
  result?: AccommodationPageResponse;
}

export interface Transportation {
  name?: string;
  type?: string;
  latitude?: number;
  longitude?: number;
  distance?: string;
  byFoot?: DistanceInfo;
  byCar?: DistanceInfo;
}

export interface AccommodationCountResponse {
  accommodationCount?: number;
}

/**
 * 응답 유형
 */
export type StandardResponseAccommodationCountResponseResponseType =
  | "SUCCESS"
  | "ERROR";
/**
 * API 응답의 표준 형식을 정의하는 클래스
 */
export interface StandardResponseAccommodationCountResponse {
  /** 응답 유형 */
  responseType?: StandardResponseAccommodationCountResponseResponseType;
  /** 응답 결과 데이터 */
  result?: AccommodationCountResponse;
}

export type GetAccommodationByTableIdAndUserIdParams = {
  /**
   * 숙소가 포함된 테이블의 ID
   */
  tableId: number;
  /**
   * 페이지 번호
   */
  page: number;
  /**
   * 페이지 크기
   */
  size: number;
  /**
   * 유저 ID, 없는 경우 모든 유저가 생성한 숙소 목록을 반환합니다.
   */
  userId?: number;
};

export type GetAccommodationCountByTableIdParams = {
  /**
   * 숙소가 포함된 테이블의 ID
   */
  tableId: number;
  /**
   * 유저 ID, 없는 경우 모든 유저가 생성한 숙소 목록을 반환합니다.
   */
  userId?: number;
};
