/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * YAPP26 WEB2
 * SSOK 서비스 API 명세
 * OpenAPI spec version: v1
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";
import { http } from "./api/http";
import type {
  AccommodationRegisterRequest,
  AddAccommodationToComparisonTableParams,
  CreateComparisonTableRequest,
  GetAccommodationByBoardIdAndUserIdParams,
  GetAccommodationCountByBoardIdParams,
  StandardResponseAccommodationCountResponse,
  StandardResponseAccommodationPageResponse,
  StandardResponseAccommodationRegisterResponse,
  StandardResponseAccommodationResponse,
  StandardResponseComparisonFactorList,
  StandardResponseComparisonTableResponse,
  StandardResponseCreateComparisonTableResponse,
} from "./index.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 비교표 메타 데이터와 포함된 숙소 정보 리스트를 조회합니다.
 * @summary 비교표 조회
 */
export type getComparisonTableResponse200 = {
  data: StandardResponseComparisonTableResponse;
  status: 200;
};

export type getComparisonTableResponseComposite = getComparisonTableResponse200;

export type getComparisonTableResponse = getComparisonTableResponseComposite & {
  headers: Headers;
};

export const getGetComparisonTableUrl = (tableId: number) => {
  return `https://api.ssok.info/api/comparison/${tableId}`;
};

export const getComparisonTable = async (
  tableId: number,
  options?: RequestInit,
): Promise<getComparisonTableResponse> => {
  return http<getComparisonTableResponse>(getGetComparisonTableUrl(tableId), {
    ...options,
    method: "GET",
  });
};

export const getGetComparisonTableQueryKey = (tableId?: number) => {
  return [`https://api.ssok.info/api/comparison/${tableId}`] as const;
};

export const getGetComparisonTableQueryOptions = <
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetComparisonTableQueryKey(tableId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getComparisonTable>>
  > = ({ signal }) =>
    getComparisonTable(tableId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!tableId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getComparisonTable>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetComparisonTableQueryResult = NonNullable<
  Awaited<ReturnType<typeof getComparisonTable>>
>;
export type GetComparisonTableQueryError = unknown;

export function useGetComparisonTable<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComparisonTable>>,
          TError,
          Awaited<ReturnType<typeof getComparisonTable>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetComparisonTable<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComparisonTable>>,
          TError,
          Awaited<ReturnType<typeof getComparisonTable>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetComparisonTable<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 비교표 조회
 */

export function useGetComparisonTable<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetComparisonTableQueryOptions(tableId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 비교표 조회
 */
export const prefetchGetComparisonTableQuery = async <
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  tableId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
): Promise<QueryClient> => {
  const queryOptions = getGetComparisonTableQueryOptions(tableId, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getGetComparisonTableSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetComparisonTableQueryKey(tableId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getComparisonTable>>
  > = ({ signal }) =>
    getComparisonTable(tableId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getComparisonTable>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetComparisonTableSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getComparisonTable>>
>;
export type GetComparisonTableSuspenseQueryError = unknown;

export function useGetComparisonTableSuspense<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetComparisonTableSuspense<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetComparisonTableSuspense<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
/**
 * @summary 비교표 조회
 */

export function useGetComparisonTableSuspense<
  TData = Awaited<ReturnType<typeof getComparisonTable>>,
  TError = unknown,
>(
  tableId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonTable>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
} {
  const queryOptions = getGetComparisonTableSuspenseQueryOptions(
    tableId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 비교표 메타 데이터와 비교 기준 항목을 수정합니다.
 * @summary 비교표 수정
 */
export type updateComparisonTableResponse200 = {
  data: StandardResponseComparisonTableResponse;
  status: 200;
};

export type updateComparisonTableResponseComposite =
  updateComparisonTableResponse200;

export type updateComparisonTableResponse =
  updateComparisonTableResponseComposite & {
    headers: Headers;
  };

export const getUpdateComparisonTableUrl = (tableId: number) => {
  return `https://api.ssok.info/api/comparison/${tableId}`;
};

export const updateComparisonTable = async (
  tableId: number,
  createComparisonTableRequest: CreateComparisonTableRequest,
  options?: RequestInit,
): Promise<updateComparisonTableResponse> => {
  return http<updateComparisonTableResponse>(
    getUpdateComparisonTableUrl(tableId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createComparisonTableRequest),
    },
  );
};

export const getUpdateComparisonTableMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateComparisonTable>>,
    TError,
    { tableId: number; data: CreateComparisonTableRequest },
    TContext
  >;
  request?: SecondParameter<typeof http>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateComparisonTable>>,
  TError,
  { tableId: number; data: CreateComparisonTableRequest },
  TContext
> => {
  const mutationKey = ["updateComparisonTable"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateComparisonTable>>,
    { tableId: number; data: CreateComparisonTableRequest }
  > = (props) => {
    const { tableId, data } = props ?? {};

    return updateComparisonTable(tableId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateComparisonTableMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateComparisonTable>>
>;
export type UpdateComparisonTableMutationBody = CreateComparisonTableRequest;
export type UpdateComparisonTableMutationError = unknown;

/**
 * @summary 비교표 수정
 */
export const useUpdateComparisonTable = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateComparisonTable>>,
      TError,
      { tableId: number; data: CreateComparisonTableRequest },
      TContext
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateComparisonTable>>,
  TError,
  { tableId: number; data: CreateComparisonTableRequest },
  TContext
> => {
  const mutationOptions = getUpdateComparisonTableMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 비교표에 새로운 숙소를 추가합니다.
 * @summary 비교표 숙소 추가
 */
export type addAccommodationToComparisonTableResponse200 = {
  data: StandardResponseComparisonTableResponse;
  status: 200;
};

export type addAccommodationToComparisonTableResponseComposite =
  addAccommodationToComparisonTableResponse200;

export type addAccommodationToComparisonTableResponse =
  addAccommodationToComparisonTableResponseComposite & {
    headers: Headers;
  };

export const getAddAccommodationToComparisonTableUrl = (
  tableId: number,
  params: AddAccommodationToComparisonTableParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.ssok.info/api/comparison/${tableId}?${stringifiedParams}`
    : `https://api.ssok.info/api/comparison/${tableId}`;
};

export const addAccommodationToComparisonTable = async (
  tableId: number,
  params: AddAccommodationToComparisonTableParams,
  options?: RequestInit,
): Promise<addAccommodationToComparisonTableResponse> => {
  return http<addAccommodationToComparisonTableResponse>(
    getAddAccommodationToComparisonTableUrl(tableId, params),
    {
      ...options,
      method: "PATCH",
    },
  );
};

export const getAddAccommodationToComparisonTableMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addAccommodationToComparisonTable>>,
    TError,
    { tableId: number; params: AddAccommodationToComparisonTableParams },
    TContext
  >;
  request?: SecondParameter<typeof http>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addAccommodationToComparisonTable>>,
  TError,
  { tableId: number; params: AddAccommodationToComparisonTableParams },
  TContext
> => {
  const mutationKey = ["addAccommodationToComparisonTable"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addAccommodationToComparisonTable>>,
    { tableId: number; params: AddAccommodationToComparisonTableParams }
  > = (props) => {
    const { tableId, params } = props ?? {};

    return addAccommodationToComparisonTable(tableId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddAccommodationToComparisonTableMutationResult = NonNullable<
  Awaited<ReturnType<typeof addAccommodationToComparisonTable>>
>;

export type AddAccommodationToComparisonTableMutationError = unknown;

/**
 * @summary 비교표 숙소 추가
 */
export const useAddAccommodationToComparisonTable = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addAccommodationToComparisonTable>>,
      TError,
      { tableId: number; params: AddAccommodationToComparisonTableParams },
      TContext
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addAccommodationToComparisonTable>>,
  TError,
  { tableId: number; params: AddAccommodationToComparisonTableParams },
  TContext
> => {
  const mutationOptions =
    getAddAccommodationToComparisonTableMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 비교표 이름, 숙소 ID 리스트, 비교 기준 항목을 받아서 비교표 메타 데이터를 생성합니다.
 * @summary 비교표 생성
 */
export type createComparisonTableResponse200 = {
  data: StandardResponseCreateComparisonTableResponse;
  status: 200;
};

export type createComparisonTableResponseComposite =
  createComparisonTableResponse200;

export type createComparisonTableResponse =
  createComparisonTableResponseComposite & {
    headers: Headers;
  };

export const getCreateComparisonTableUrl = () => {
  return `https://api.ssok.info/api/comparison/new`;
};

export const createComparisonTable = async (
  createComparisonTableRequest: CreateComparisonTableRequest,
  options?: RequestInit,
): Promise<createComparisonTableResponse> => {
  return http<createComparisonTableResponse>(getCreateComparisonTableUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createComparisonTableRequest),
  });
};

export const getCreateComparisonTableMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createComparisonTable>>,
    TError,
    { data: CreateComparisonTableRequest },
    TContext
  >;
  request?: SecondParameter<typeof http>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createComparisonTable>>,
  TError,
  { data: CreateComparisonTableRequest },
  TContext
> => {
  const mutationKey = ["createComparisonTable"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createComparisonTable>>,
    { data: CreateComparisonTableRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createComparisonTable(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateComparisonTableMutationResult = NonNullable<
  Awaited<ReturnType<typeof createComparisonTable>>
>;
export type CreateComparisonTableMutationBody = CreateComparisonTableRequest;
export type CreateComparisonTableMutationError = unknown;

/**
 * @summary 비교표 생성
 */
export const useCreateComparisonTable = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createComparisonTable>>,
      TError,
      { data: CreateComparisonTableRequest },
      TContext
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createComparisonTable>>,
  TError,
  { data: CreateComparisonTableRequest },
  TContext
> => {
  const mutationOptions = getCreateComparisonTableMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 링크를 첨부하여 숙소 카드를 등록합니다.
 * @summary 숙소 카드 등록
 */
export type registerAccommodationCardResponse200 = {
  data: StandardResponseAccommodationRegisterResponse;
  status: 200;
};

export type registerAccommodationCardResponseComposite =
  registerAccommodationCardResponse200;

export type registerAccommodationCardResponse =
  registerAccommodationCardResponseComposite & {
    headers: Headers;
  };

export const getRegisterAccommodationCardUrl = () => {
  return `https://api.ssok.info/api/accommodations/register`;
};

export const registerAccommodationCard = async (
  accommodationRegisterRequest: AccommodationRegisterRequest,
  options?: RequestInit,
): Promise<registerAccommodationCardResponse> => {
  return http<registerAccommodationCardResponse>(
    getRegisterAccommodationCardUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(accommodationRegisterRequest),
    },
  );
};

export const getRegisterAccommodationCardMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerAccommodationCard>>,
    TError,
    { data: AccommodationRegisterRequest },
    TContext
  >;
  request?: SecondParameter<typeof http>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerAccommodationCard>>,
  TError,
  { data: AccommodationRegisterRequest },
  TContext
> => {
  const mutationKey = ["registerAccommodationCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerAccommodationCard>>,
    { data: AccommodationRegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return registerAccommodationCard(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterAccommodationCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerAccommodationCard>>
>;
export type RegisterAccommodationCardMutationBody =
  AccommodationRegisterRequest;
export type RegisterAccommodationCardMutationError = unknown;

/**
 * @summary 숙소 카드 등록
 */
export const useRegisterAccommodationCard = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerAccommodationCard>>,
      TError,
      { data: AccommodationRegisterRequest },
      TContext
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registerAccommodationCard>>,
  TError,
  { data: AccommodationRegisterRequest },
  TContext
> => {
  const mutationOptions = getRegisterAccommodationCardMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 클라이언트 요청 시 카카오 OAuth2 인가 페이지로 리다이렉트하고, 인가 완료 시 쿠키에 ACCESS TOKEN 및 REFRESH TOKEN을 발급합니다.
 * @summary 카카오 소셜 로그인 리다이렉션
 */
export type redirectToKakaoAuthorizationResponse302 = {
  data: null;
  status: 302;
};

export type redirectToKakaoAuthorizationResponseComposite =
  redirectToKakaoAuthorizationResponse302;

export type redirectToKakaoAuthorizationResponse =
  redirectToKakaoAuthorizationResponseComposite & {
    headers: Headers;
  };

export const getRedirectToKakaoAuthorizationUrl = () => {
  return `https://api.ssok.info/api/oauth/kakao`;
};

export const redirectToKakaoAuthorization = async (
  options?: RequestInit,
): Promise<redirectToKakaoAuthorizationResponse> => {
  return http<redirectToKakaoAuthorizationResponse>(
    getRedirectToKakaoAuthorizationUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRedirectToKakaoAuthorizationQueryKey = () => {
  return [`https://api.ssok.info/api/oauth/kakao`] as const;
};

export const getRedirectToKakaoAuthorizationQueryOptions = <
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof http>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRedirectToKakaoAuthorizationQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof redirectToKakaoAuthorization>>
  > = ({ signal }) =>
    redirectToKakaoAuthorization({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type RedirectToKakaoAuthorizationQueryResult = NonNullable<
  Awaited<ReturnType<typeof redirectToKakaoAuthorization>>
>;
export type RedirectToKakaoAuthorizationQueryError = null;

export function useRedirectToKakaoAuthorization<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
          TError,
          Awaited<ReturnType<typeof redirectToKakaoAuthorization>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useRedirectToKakaoAuthorization<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
          TError,
          Awaited<ReturnType<typeof redirectToKakaoAuthorization>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useRedirectToKakaoAuthorization<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 카카오 소셜 로그인 리다이렉션
 */

export function useRedirectToKakaoAuthorization<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getRedirectToKakaoAuthorizationQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 카카오 소셜 로그인 리다이렉션
 */
export const prefetchRedirectToKakaoAuthorizationQuery = async <
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
): Promise<QueryClient> => {
  const queryOptions = getRedirectToKakaoAuthorizationQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getRedirectToKakaoAuthorizationSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof http>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRedirectToKakaoAuthorizationQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof redirectToKakaoAuthorization>>
  > = ({ signal }) =>
    redirectToKakaoAuthorization({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type RedirectToKakaoAuthorizationSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof redirectToKakaoAuthorization>>
>;
export type RedirectToKakaoAuthorizationSuspenseQueryError = null;

export function useRedirectToKakaoAuthorizationSuspense<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useRedirectToKakaoAuthorizationSuspense<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useRedirectToKakaoAuthorizationSuspense<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
/**
 * @summary 카카오 소셜 로그인 리다이렉션
 */

export function useRedirectToKakaoAuthorizationSuspense<
  TData = Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
  TError = null,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof redirectToKakaoAuthorization>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
} {
  const queryOptions =
    getRedirectToKakaoAuthorizationSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 비교 기준 항목 Enum 리스트를 반환합니다.
 * @summary 비교표 기준 항목 Enum 리스트
 */
export type getComparisonFactorListResponse200 = {
  data: StandardResponseComparisonFactorList;
  status: 200;
};

export type getComparisonFactorListResponseComposite =
  getComparisonFactorListResponse200;

export type getComparisonFactorListResponse =
  getComparisonFactorListResponseComposite & {
    headers: Headers;
  };

export const getGetComparisonFactorListUrl = () => {
  return `https://api.ssok.info/api/comparison/factors`;
};

export const getComparisonFactorList = async (
  options?: RequestInit,
): Promise<getComparisonFactorListResponse> => {
  return http<getComparisonFactorListResponse>(
    getGetComparisonFactorListUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetComparisonFactorListQueryKey = () => {
  return [`https://api.ssok.info/api/comparison/factors`] as const;
};

export const getGetComparisonFactorListQueryOptions = <
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getComparisonFactorList>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof http>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetComparisonFactorListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getComparisonFactorList>>
  > = ({ signal }) => getComparisonFactorList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getComparisonFactorList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetComparisonFactorListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getComparisonFactorList>>
>;
export type GetComparisonFactorListQueryError = unknown;

export function useGetComparisonFactorList<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComparisonFactorList>>,
          TError,
          Awaited<ReturnType<typeof getComparisonFactorList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetComparisonFactorList<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComparisonFactorList>>,
          TError,
          Awaited<ReturnType<typeof getComparisonFactorList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetComparisonFactorList<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 비교표 기준 항목 Enum 리스트
 */

export function useGetComparisonFactorList<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetComparisonFactorListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 비교표 기준 항목 Enum 리스트
 */
export const prefetchGetComparisonFactorListQuery = async <
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
): Promise<QueryClient> => {
  const queryOptions = getGetComparisonFactorListQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getGetComparisonFactorListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getComparisonFactorList>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof http>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetComparisonFactorListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getComparisonFactorList>>
  > = ({ signal }) => getComparisonFactorList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getComparisonFactorList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetComparisonFactorListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getComparisonFactorList>>
>;
export type GetComparisonFactorListSuspenseQueryError = unknown;

export function useGetComparisonFactorListSuspense<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetComparisonFactorListSuspense<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetComparisonFactorListSuspense<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
/**
 * @summary 비교표 기준 항목 Enum 리스트
 */

export function useGetComparisonFactorListSuspense<
  TData = Awaited<ReturnType<typeof getComparisonFactorList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComparisonFactorList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
} {
  const queryOptions = getGetComparisonFactorListSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 숙소 ID로 숙소 정보를 조회합니다.
 * @summary 숙소 단건 조회
 */
export type getAccommodationByIdResponse200 = {
  data: StandardResponseAccommodationResponse;
  status: 200;
};

export type getAccommodationByIdResponseComposite =
  getAccommodationByIdResponse200;

export type getAccommodationByIdResponse =
  getAccommodationByIdResponseComposite & {
    headers: Headers;
  };

export const getGetAccommodationByIdUrl = (accommodationId: number) => {
  return `https://api.ssok.info/api/accommodations/${accommodationId}`;
};

export const getAccommodationById = async (
  accommodationId: number,
  options?: RequestInit,
): Promise<getAccommodationByIdResponse> => {
  return http<getAccommodationByIdResponse>(
    getGetAccommodationByIdUrl(accommodationId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAccommodationByIdQueryKey = (accommodationId?: number) => {
  return [
    `https://api.ssok.info/api/accommodations/${accommodationId}`,
  ] as const;
};

export const getGetAccommodationByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAccommodationByIdQueryKey(accommodationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccommodationById>>
  > = ({ signal }) =>
    getAccommodationById(accommodationId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!accommodationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccommodationById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAccommodationByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccommodationById>>
>;
export type GetAccommodationByIdQueryError = unknown;

export function useGetAccommodationById<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationById>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationById<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationById>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAccommodationById<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 숙소 단건 조회
 */

export function useGetAccommodationById<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetAccommodationByIdQueryOptions(
    accommodationId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 숙소 단건 조회
 */
export const prefetchGetAccommodationByIdQuery = async <
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  accommodationId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
): Promise<QueryClient> => {
  const queryOptions = getGetAccommodationByIdQueryOptions(
    accommodationId,
    options,
  );

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getGetAccommodationByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAccommodationByIdQueryKey(accommodationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccommodationById>>
  > = ({ signal }) =>
    getAccommodationById(accommodationId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAccommodationById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAccommodationByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccommodationById>>
>;
export type GetAccommodationByIdSuspenseQueryError = unknown;

export function useGetAccommodationByIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationByIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationByIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
/**
 * @summary 숙소 단건 조회
 */

export function useGetAccommodationByIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationById>>,
  TError = unknown,
>(
  accommodationId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
} {
  const queryOptions = getGetAccommodationByIdSuspenseQueryOptions(
    accommodationId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 숙소 목록을 조회합니다.
 * @summary 숙소 목록 조회
 */
export type getAccommodationByBoardIdAndUserIdResponse200 = {
  data: StandardResponseAccommodationPageResponse;
  status: 200;
};

export type getAccommodationByBoardIdAndUserIdResponseComposite =
  getAccommodationByBoardIdAndUserIdResponse200;

export type getAccommodationByBoardIdAndUserIdResponse =
  getAccommodationByBoardIdAndUserIdResponseComposite & {
    headers: Headers;
  };

export const getGetAccommodationByBoardIdAndUserIdUrl = (
  params: GetAccommodationByBoardIdAndUserIdParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.ssok.info/api/accommodations/search?${stringifiedParams}`
    : `https://api.ssok.info/api/accommodations/search`;
};

export const getAccommodationByBoardIdAndUserId = async (
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: RequestInit,
): Promise<getAccommodationByBoardIdAndUserIdResponse> => {
  return http<getAccommodationByBoardIdAndUserIdResponse>(
    getGetAccommodationByBoardIdAndUserIdUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAccommodationByBoardIdAndUserIdQueryKey = (
  params?: GetAccommodationByBoardIdAndUserIdParams,
) => {
  return [
    `https://api.ssok.info/api/accommodations/search`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAccommodationByBoardIdAndUserIdInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  >,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAccommodationByBoardIdAndUserIdQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  > = ({ signal }) =>
    getAccommodationByBoardIdAndUserId(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAccommodationByBoardIdAndUserIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
>;
export type GetAccommodationByBoardIdAndUserIdInfiniteQueryError = unknown;

export function useGetAccommodationByBoardIdAndUserIdInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  >,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationByBoardIdAndUserIdInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  >,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationByBoardIdAndUserIdInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  >,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
/**
 * @summary 숙소 목록 조회
 */

export function useGetAccommodationByBoardIdAndUserIdInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  >,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
} {
  const queryOptions =
    getGetAccommodationByBoardIdAndUserIdInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 숙소 목록 조회
 */
export const prefetchGetAccommodationByBoardIdAndUserIdInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
): Promise<QueryClient> => {
  const queryOptions =
    getGetAccommodationByBoardIdAndUserIdInfiniteQueryOptions(params, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getGetAccommodationByBoardIdAndUserIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAccommodationByBoardIdAndUserIdQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  > = ({ signal }) =>
    getAccommodationByBoardIdAndUserId(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAccommodationByBoardIdAndUserIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
>;
export type GetAccommodationByBoardIdAndUserIdQueryError = unknown;

export function useGetAccommodationByBoardIdAndUserId<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationByBoardIdAndUserId<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAccommodationByBoardIdAndUserId<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 숙소 목록 조회
 */

export function useGetAccommodationByBoardIdAndUserId<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetAccommodationByBoardIdAndUserIdQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 숙소 목록 조회
 */
export const prefetchGetAccommodationByBoardIdAndUserIdQuery = async <
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
): Promise<QueryClient> => {
  const queryOptions = getGetAccommodationByBoardIdAndUserIdQueryOptions(
    params,
    options,
  );

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getGetAccommodationByBoardIdAndUserIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAccommodationByBoardIdAndUserIdQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
  > = ({ signal }) =>
    getAccommodationByBoardIdAndUserId(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAccommodationByBoardIdAndUserIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>
>;
export type GetAccommodationByBoardIdAndUserIdSuspenseQueryError = unknown;

export function useGetAccommodationByBoardIdAndUserIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationByBoardIdAndUserIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationByBoardIdAndUserIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
/**
 * @summary 숙소 목록 조회
 */

export function useGetAccommodationByBoardIdAndUserIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
  TError = unknown,
>(
  params: GetAccommodationByBoardIdAndUserIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationByBoardIdAndUserId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
} {
  const queryOptions =
    getGetAccommodationByBoardIdAndUserIdSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 여행보드에 포함된 숙소의 개수를 조회합니다.
 * @summary 여행보드 숙소 개수 조회
 */
export type getAccommodationCountByBoardIdResponse200 = {
  data: StandardResponseAccommodationCountResponse;
  status: 200;
};

export type getAccommodationCountByBoardIdResponseComposite =
  getAccommodationCountByBoardIdResponse200;

export type getAccommodationCountByBoardIdResponse =
  getAccommodationCountByBoardIdResponseComposite & {
    headers: Headers;
  };

export const getGetAccommodationCountByBoardIdUrl = (
  params: GetAccommodationCountByBoardIdParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.ssok.info/api/accommodations/count?${stringifiedParams}`
    : `https://api.ssok.info/api/accommodations/count`;
};

export const getAccommodationCountByBoardId = async (
  params: GetAccommodationCountByBoardIdParams,
  options?: RequestInit,
): Promise<getAccommodationCountByBoardIdResponse> => {
  return http<getAccommodationCountByBoardIdResponse>(
    getGetAccommodationCountByBoardIdUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAccommodationCountByBoardIdQueryKey = (
  params?: GetAccommodationCountByBoardIdParams,
) => {
  return [
    `https://api.ssok.info/api/accommodations/count`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAccommodationCountByBoardIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAccommodationCountByBoardIdQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccommodationCountByBoardId>>
  > = ({ signal }) =>
    getAccommodationCountByBoardId(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAccommodationCountByBoardIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccommodationCountByBoardId>>
>;
export type GetAccommodationCountByBoardIdQueryError = unknown;

export function useGetAccommodationCountByBoardId<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationCountByBoardId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationCountByBoardId<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
          TError,
          Awaited<ReturnType<typeof getAccommodationCountByBoardId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAccommodationCountByBoardId<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary 여행보드 숙소 개수 조회
 */

export function useGetAccommodationCountByBoardId<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetAccommodationCountByBoardIdQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 여행보드 숙소 개수 조회
 */
export const prefetchGetAccommodationCountByBoardIdQuery = async <
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
): Promise<QueryClient> => {
  const queryOptions = getGetAccommodationCountByBoardIdQueryOptions(
    params,
    options,
  );

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getGetAccommodationCountByBoardIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAccommodationCountByBoardIdQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccommodationCountByBoardId>>
  > = ({ signal }) =>
    getAccommodationCountByBoardId(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAccommodationCountByBoardIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccommodationCountByBoardId>>
>;
export type GetAccommodationCountByBoardIdSuspenseQueryError = unknown;

export function useGetAccommodationCountByBoardIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationCountByBoardIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAccommodationCountByBoardIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
/**
 * @summary 여행보드 숙소 개수 조회
 */

export function useGetAccommodationCountByBoardIdSuspense<
  TData = Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
  TError = unknown,
>(
  params: GetAccommodationCountByBoardIdParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAccommodationCountByBoardId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof http>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
} {
  const queryOptions = getGetAccommodationCountByBoardIdSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
