import { type ClassValue, clsx } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      text: [
        "title1-semi36",
        "title2-medi28",
        "title3-bold24",
        "heading1-semi20",
        "heading2-semi18",
        "heading2-medi18",
        "body1-bold16",
        "body1-semi16",
        "body1-medi16",
        "body1-regular16",
        "body2-medi14",
        "body2-regular14",
        "body3-semi15",
        "caption1-semi12",
        "caption1-medi12",
        "caption2-medi11",
        "caption2-regular11",

        "white",
        "black",
        "primary",

        "neutral-100",
        "neutral-99",
        "neutral-98",
        "neutral-95",
        "neutral-90",
        "neutral-80",
        "neutral-70",
        "neutral-60",
        "neutral-50",
        "neutral-40",
        "neutral-35",
        "neutral-30",
        "neutral-25",
        "neutral-20",
        "neutral-15",
        "neutral-10",
        "neutral-5",
        "neutral-0",

        "neutral-variant-100",
        "neutral-variant-99",
        "neutral-variant-98",
        "neutral-variant-95",
        "neutral-variant-90",
        "neutral-variant-80",
        "neutral-variant-70",
        "neutral-variant-60",
        "neutral-variant-50",
        "neutral-variant-40",
        "neutral-variant-35",
        "neutral-variant-30",
        "neutral-variant-25",
        "neutral-variant-20",
        "neutral-variant-15",
        "neutral-variant-10",
        "neutral-variant-5",
        "neutral-variant-0",

        "primary-100",
        "primary-99",
        "primary-98",
        "primary-95",
        "primary-90",
        "primary-80",
        "primary-70",
        "primary-60",
        "primary-50",
        "primary-40",
        "primary-35",
        "primary-30",
        "primary-25",
        "primary-20",
        "primary-15",
        "primary-10",
        "primary-5",
        "primary-0",

        "secondary-100",
        "secondary-99",
        "secondary-98",
        "secondary-95",
        "secondary-90",
        "secondary-80",
        "secondary-70",
        "secondary-60",
        "secondary-50",
        "secondary-40",
        "secondary-35",
        "secondary-30",
        "secondary-25",
        "secondary-20",
        "secondary-15",
        "secondary-10",
        "secondary-5",
        "secondary-0",

        "error-100",
        "error-99",
        "error-98",
        "error-95",
        "error-90",
        "error-80",
        "error-70",
        "error-60",
        "error-50",
        "error-40",
        "error-35",
        "error-30",
        "error-25",
        "error-20",
        "error-15",
        "error-10",
        "error-5",
        "error-0",

        "tertiary-100",
        "tertiary-99",
        "tertiary-98",
        "tertiary-95",
        "tertiary-90",
        "tertiary-80",
        "tertiary-70",
        "tertiary-60",
        "tertiary-50",
        "tertiary-40",
        "tertiary-35",
        "tertiary-30",
        "tertiary-25",
        "tertiary-20",
        "tertiary-15",
        "tertiary-10",
        "tertiary-5",
        "tertiary-0",

        "opacity-3-75",
        "opacity-7",
        "opacity-12",

        "shadow-floating",
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
