name: ci

on:
  push:
    branches:
      - main  
  pull_request:

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Node.js version from package.json
        id: get_node_version
        run: echo "version=$(jq -r '.engines.node' package.json)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with: 
          node-version: ${{ steps.get_node_version.outputs.version }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4


      - run: pnpm install --frozen-lockfile
      - run: pnpm exec biome ci

  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Extract Node.js version from package.json
          id: get_node_version
          run: echo "version=$(jq -r '.engines.node' package.json)" >> $GITHUB_OUTPUT

        - uses: actions/setup-node@v4
          with: 
            node-version: ${{ steps.get_node_version.outputs.version }}
  
        - name: Setup Pnpm
          uses: pnpm/action-setup@v4

        - run: pnpm install --frozen-lockfile
        - run: pnpm run build
  
