name: ci

on:
  push:
    branches:
      - main  
  pull_request:

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec biome ci

  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4

  
        - name: Setup Pnpm
          uses: pnpm/action-setup@v4

        - run: pnpm install --frozen-lockfile
        - run: pnpm run build
  
